language: node_js

node_js:
- '10'

services:
- docker
before_install:
- cd ui-src
- npm install
- npm run build
- npm run start &
- cd ..
- docker pull holochain/holochain-rust:latest
script:
- docker run holochain/holochain-rust:latest /bin/sh -c "npm run hc:test-chat"
- cd ui-automation
- npm install
- npm test
- curl http://localhost:4141
- cd ..
- cd ui-src
- npm run coverage