language: node_js

node_js:
- '10'

services:
- docker
before_install:
- docker pull holochain/holochain-rust:latest
script:
- docker run -v ${TRAVIS_BUILD_DIR}:/holochain-ui/ holochain/holochain-rust:latest /bin/sh -c "cd /holochain-ui/dna-src/holo-chat && hc test"