[[agents]]
id = "test_agent"
name = "HoloTester"
key_file = "holo_tester.key"



[[dnas]]
id = "chat_dna"
file = "dna/holo-chat.hcpkg"
hash = "QmN0tARea1#ashChat"

[[dnas]]
id = "vault_dna"
file = "dna/holo-vault.hcpkg"
hash = "QmN0tARea1#ashVault"



[[instances]]
id = "holo-chat"
dna = "chat_dna"
agent = "test_agent"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp-storage"

[[instances]]
id = "holo-vault"
dna = "vault_dna"
agent = "test_agent"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp-storage"




[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3400
[[interfaces.instances]]
id = "holo-chat"
[[interfaces.instances]]
id = "holo-vault"