version: '3'

services:

  bootstrap:
    image: holochain/holochain-proto:develop
    ports:
      - "3142:3142"
    command: bs

  holochain-ui1:
    image: holochain/holochain-proto:develop
    ports:
      - "4141:4141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/holochain-ui"
    command: bash -c "cd /holochain-ui && apt-get update && apt-get install -y moreutils jq && bash ./start_apps Willem 0 bootstrap:3142"

  holochain-ui2:
    image: holochain/holochain-proto:develop
    ports:
      - "4142:4142"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/holochain-ui"
    command: bash -c "cd /holochain-ui && apt-get update && apt-get install -y moreutils jq && bash ./start_apps Philip 1 bootstrap:3142"

  holochain-ui3:
    image: holochain/holochain-proto:develop
    ports:
      - "4143:4143"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/holochain-ui"
    command: bash -c "cd /holochain-ui && apt-get update && apt-get install -y moreutils jq && bash ./start_apps Micah 2 bootstrap:3142"
