version: '2'

services:

  bootstrap:
    image: holochain/holochain-proto:develop
    ports:
      - "3142:3142"
    command: bs

  holochain-ui1:
    image: holochain/holochain-proto:develop
    ports:
      - "3141:3141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/holochain-ui"
    command: bash -c "cd /holochain-ui; hcdev -agentID=lucy -bootstrapServer=bootstrap:3142 web 3141"

  holochain-ui2:
    image: holochain/holochain-proto:develop
    ports:
      - "4141:4141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/holochain-ui"
    command: bash -c "cd /holochain-ui; hcdev -agentID=phil -bootstrapServer=bootstrap:3142 web 4141"

  holochain-ui3:
    image: holochain/holochain-proto:develop
    ports:
      - "5141:5141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/holochain-ui"
    command: bash -c "cd /holochain-ui; hcdev -agentID=clarence -bootstrapServer=bootstrap:3142 web 5141"
